[
  {
    "title": "Next.jsで自作ブログを作る②",
    "link": "https://note.com/kuwaharu/n/n40d0a0f046fb",
    "published": "Sun, 17 Nov 2024 11:22:59 +0900",
    "summary": "<p id=\"ae69cf4f-b78b-4210-bfaf-de3413a4edcd\" name=\"ae69cf4f-b78b-4210-bfaf-de3413a4edcd\">こちらの続きです。</p><figure id=\"08f9c742-8202-4e2f-a501-77c2924b89fb\" name=\"08f9c742-8202-4e2f-a501-77c2924b89fb\"></figure><br /><a href=\"https://note.com/kuwaharu/n/n40d0a0f046fb\">続きをみる</a>",
    "creator_name": "",
    "creator_image": ""
  },
  {
    "title": "Next.jsで自作ブログを作る①",
    "link": "https://note.com/kuwaharu/n/n07b0630682de",
    "published": "Fri, 08 Nov 2024 00:17:53 +0900",
    "summary": "<p id=\"e337ddf1-40e3-47e5-9972-b456cc951079\" name=\"e337ddf1-40e3-47e5-9972-b456cc951079\"><a href=\"https://tech.kuwaharu.com/\" rel=\"nofollow noopener\" target=\"_blank\">自作ブログ</a></p><h2 id=\"6179a4a0-e9d7-4a02-9322-06d8b4784474\" name=\"6179a4a0-e9d7-4a02-9322-06d8b4784474\">ブログを自作しようと思った経緯</h2><br /><a href=\"https://note.com/kuwaharu/n/n07b0630682de\">続きをみる</a>",
    "creator_name": "",
    "creator_image": ""
  },
  {
    "title": "Pythonがエラーを出さずに終了した時に原因を調べる(faulthandlerモジュール)",
    "link": "https://note.com/kuwaharu/n/nc7f692b8204d",
    "published": "Sat, 02 Nov 2024 14:30:11 +0900",
    "summary": "<p id=\"8e9d9b08-ec8e-4389-903d-20b8b0978c4c\" name=\"8e9d9b08-ec8e-4389-903d-20b8b0978c4c\">pythonで外部ライブラリ（特にCで書かれたもの）を使用していると、python自体がキャッチできないエラーが起き、何も表示されずに異常終了することがあります。私の場合mysql-connector-pythonを使用した時に起こりました。</p><p id=\"770c4382-494d-4e46-8ecb-716f965876cc\" name=\"770c4382-494d-4e46-8ecb-716f965876cc\">そのような時に役に立つのが標準ライブライのfaulthandlerモジュールです。</p><br /><a href=\"https://note.com/kuwaharu/n/nc7f692b8204d\">続きをみる</a>",
    "creator_name": "",
    "creator_image": ""
  },
  {
    "title": "Python ModuleNotFoundErrorの解決方法",
    "link": "https://note.com/kuwaharu/n/nf3ebd9f9ba4a",
    "published": "Wed, 23 Oct 2024 16:15:49 +0900",
    "summary": "<pre id=\"1579d515-83a5-4d41-95b9-9735c22f5996\" name=\"1579d515-83a5-4d41-95b9-9735c22f5996\"><code>ModuleNotFoundError: No module named 〇〇〇</code></pre><p id=\"13b85028-2776-4992-96ba-d0d06e96385f\" name=\"13b85028-2776-4992-96ba-d0d06e96385f\">今回はPythonのこのエラーの解決方法を原因も含めいくつか紹介します。</p><br /><a href=\"https://note.com/kuwaharu/n/nf3ebd9f9ba4a\">続きをみる</a>",
    "creator_name": "",
    "creator_image": ""
  },
  {
    "title": "情報処理安全確保支援士受験報告",
    "link": "https://note.com/kuwaharu/n/n7cd3e8d12c9f",
    "published": "Tue, 15 Oct 2024 14:32:34 +0900",
    "summary": "<p id=\"99b9752d-786c-4c26-9054-1979c4b50334\" name=\"99b9752d-786c-4c26-9054-1979c4b50334\">2024年10月13日、情報処理安全確保支援士の試験を受験してきました。前回の春期試験で応用情報技術者試験に合格していたので午前Iは免除で、午前IIから受験しました。</p><h2 id=\"f16cdfb6-b159-410b-a5e6-36624271d6c2\" name=\"f16cdfb6-b159-410b-a5e6-36624271d6c2\">午前Ⅱ自己採点結果</h2><br /><a href=\"https://note.com/kuwaharu/n/n7cd3e8d12c9f\">続きをみる</a>",
    "creator_name": "",
    "creator_image": ""
  }
]